// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Province struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int64       `json:"id"`
	Username  string      `json:"username"`
	ProvID    pgtype.Int4 `json:"prov_id"`
	CreatedAt time.Time   `json:"created_at"`
}
