// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateProvince(ctx context.Context, arg CreateProvinceParams) (Province, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetProvince(ctx context.Context, id int64) (Province, error)
	GetUser(ctx context.Context, id int64) (User, error)
	UpdateProvince(ctx context.Context, arg UpdateProvinceParams) (Province, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
